// This file has been generated by Specta. DO NOT EDIT.

export type TauRpcApiInputTypes = { proc_name: "hello_world"; input_type: null }

export type TauRpcApiOutputTypes = { proc_name: "hello_world"; output_type: null }

const ARGS_MAP = {"":"{\"hello_world\":[]}"}
import { createTauRPCProxy as createProxy } from "taurpc"

export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)

type Router = {
	'': [TauRpcApiInputTypes, TauRpcApiOutputTypes],
}